list(APPEND CMAKE_MODULE_PATH ${CMAKE_CURRENT_LIST_DIR})
include(CMakeFindDependencyMacro)

# Include the autogenerated cmake file where the targets are defined
include(${CMAKE_CURRENT_LIST_DIR}/ads-targets.cmake)

# Set this variable to allow import of this package as a CATKIN package
set(ads_FOUND_CATKIN_PROJECT TRUE)

# Define variables for compatibility with older, non-target-based CMake consumer projects (e.g. catkin packages)
get_target_property(ads_ads_INCLUDE_DIRS ads::ads INTERFACE_INCLUDE_DIRECTORIES)
list(APPEND ads_INCLUDE_DIRS ${ads_ads_INCLUDE_DIRS})
get_target_property(ads_ads_INTERFACE_LINK_LIBRARIES ads::ads INTERFACE_LINK_LIBRARIES)
list(APPEND ads_LIBRARIES ${ads_ads_INTERFACE_LINK_LIBRARIES})
get_target_property(ads_ads_LOCATION ads::ads LOCATION)
list(APPEND ads_LIBRARIES ${ads_ads_LOCATION})
